# 监控配置
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  # 链路监控配置
  zipkin:
    base-url: http://localhost:9411
  # redis
  redis:
    host: localhost
    port: 6379
    password: admin
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，