# 监控配置
spring:
  redis:
    host: localhost
    port: 6379
    password: admin
  cloud:
    consul:
      discovery:
        tags: version=v1
        instance-id: ${spring.application.name}${random.int}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 60s
        prefer-ip-address: true
      host: zhangcc_fs.com
      port: 8500
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，
    health:
      show-details: always