# 监控配置
spring:
  redis:
    host: zhangcc_fs.com
    port: 6379
    password: admin
management:
  endpoints:
    web:
      exposure:
        #exclude: shutdown,threaddump   #此处控制的是不开放哪些端点
        include: "*" #此处控制的是开放哪些端点，
  endpoint:
    health:
      show-details: always