spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam-platform?setUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
zmc-sso:
  web-security:
    ignore-uri: /webjars/**,/doc.html,/favicon.ico,/swagger-resources/**,/v2/api-docs/**
  http-security:
    ignore-uri: /oauth/**,/login,/loginout,/actuator/**
